### ISSUE TITLE
Handle edge case: when the number of unique items in a Summary < the value of k

### ISSUE THREAD

**Issue by sytong** [buruzaemon/frequent-algorithm#12]
> Add a summary S containing identities and counts of the k most frequent items to the back of queue Q.

What if the number of unique items in a Summary < the value of k?
The likelihood may be low but it is still .... possible?

**Comment by buruzaemon** [comment]
That would result in a summary where the number of top items is less than k. This is completely possible and expected. 

For example, if an item were trending very quickly, it is possible that all b items in a basic window might all be the same category. If k were greater than 1, then we would see the situation you describe.

We need to make sure that our implementation deals with this case.

**Comment by sytong** [comment]
Will write a test to produce such scenario and then fix it

**Comment by sytong** [comment]
Fixed in Pull Request https://github.com/buruzaemon/frequent-algorithm/pull/21

**Comment by sytong** [comment]
One more case to handle for S'
Reopen the issue and will fix later today

**Comment by sytong** [comment]
Fixed... again... in Pull Request https://github.com/buruzaemon/frequent-algorithm/pull/22

I am going to call it a day :)
