### ISSUE TITLE
Enhance Algorithm: new method to return top-k statistics

### ISSUE THREAD

**Issue by buruzaemon** [buruzaemon/frequent-algorithm#17]
Right now, the top-k statistics would be obtainable with:

```
top3 = alg.statistics.select {|k,v| v > alg.delta}
```

... which perhaps requires too much knowledge of the internals of the algorithm.

Perhaps we could provide a new method that would do the work above with merely:

```
top3 = alg.report
```

**Comment by sytong** [comment]
Agree. Should be easier to test too.

**Comment by sytong** [comment]
Fixed in Pull Request https://github.com/buruzaemon/frequent-algorithm/pull/20

**Comment by sytong** [comment]
On second thought, this may not be a very good idea as the report method may be called in a premature time, e.g. when there is only one summary in the queue but N/b >= 2. 

I think the best way is to return the Top K items from the process method.
Let's handle this in Issue #2 ?

**Comment by sytong** [comment]
Removed this method in Pull Request https://github.com/buruzaemon/frequent-algorithm/pull/22

Do I need to mark it as Won'f Fix?

**Comment by sytong** [comment]
Submitted Pull Request #41 to dev-branch

**Comment by sytong** [comment]
Submitted Pull Request #43 to dev-branch to enhance the test case
