### ISSUE TITLE
Implement process method.

### ISSUE THREAD

**Issue by buruzaemon** [buruzaemon/frequent-algorithm#2]
Don't forget Yard documentation!

**Comment by buruzaemon** [comment]
And don't forget to add unit tests, too.

**Comment by sytong** [comment]
I just "saved" my progress for now.
I suggest we should break down the whole algo process into steps and then we can write unit test against each step.

We still need to write some test for the #process method as a whole but I have no idea yet.

**Comment by sytong** [comment]
I am proposing to return the Top K items from this method.
Following the algorithm, the method will only return the Top K items when the queue size is greater than N/b. Otherwise, it will return an empty {}.

**Comment by buruzaemon** [comment]
Initial implementation is done, closing this out.
