### ISSUE TITLE
Simple Visualization Tool

### ISSUE THREAD

**Issue by sytong** [buruzaemon/frequent-algorithm#27]
Can we just add a simple Rails project somewhere to demonstrate the algorithm?
Say, just display the latest trending items in a HTML table and see the data move in real time?

**Comment by buruzaemon** [comment]
Sure, that sounds like a fine idea. Just as long as that will not add any dependencies to the gem itself.

I suggest adding a new directory to this project, like `example` or something, and put the Rails project in there. 

We can leave this directory out of the gem itself, but interested people could simply fork this project.

**Comment by sytong** [comment]
Either `example` or `demo` will be good.

However I am not sure how to create a folder and leave it out of the gem?
Ignore this folder in the gemspec?

**Comment by buruzaemon** [comment]
Actually, there's nothing to do, since the gemspec file explicitly lists
which files to include.

**Comment by buruzaemon** [comment]
Will try and come up with something that will count the words, in sequence, in [Homer's Odyssey](http://classics.mit.edu/Homer/odyssey.mb.txt).

**Comment by sytong** [comment]
I think the Reactive Extension of Ruby (Rx.rb) could be useful to implement the stream which feeds data to the Frequent algorithm.
https://github.com/ReactiveX/Rx.rb

I read about this from the following Gist post:
https://gist.github.com/staltz/868e7e9bc2a7b8c1f754

**Comment by buruzaemon** [comment]
Microsoft Open Technologies? Did Hell just freeze over?
;-)

Just kidding, this looks to be very interesting. Will give this a thorough read over the weekend.

Brooke@iPhone

2015/05/01 0:30$B!"(BWillie SY Tong notifications@github.com $B$N%a%C%;!<%8(B:

**Comment by sytong** [comment]
Or create a separate 'demo' project using the tubesock stuff I did?
I think I am ready to come back on this one.

**Comment by buruzaemon** [comment]
Actually, I am more in favor of a separate demo project, Just like the tubesock.

**Comment by sytong** [comment]
And so be it. We can close this issue when that is done.

**Comment by sytong** [comment]
I have created this project for the frequent algorithm visualisation.
https://github.com/sytong/frequent-demo

Closing this issue now.
