### ISSUE TITLE
Add new test cases using String as input

### ISSUE THREAD

**Issue by sytong** [buruzaemon/frequent-algorithm#28]
Just want to make sure we won't have any surprising when handing string data.

Also what if we are getting a hybrid (string + number)? Can we handle them?

**Comment by buruzaemon** [comment]
If we use a hash as I originally envisioned, we would have:
1. keys that could be any object
2. keys that would be unique
3. keys that would necessarily be non-nil
4. constant time look-up

It really does not matter what gets used as a key, so yes, strings and combinations of string with numbers, too, will be fine.

I strongly suggest that we use a hash as data structure.

**Comment by buruzaemon** [comment]
But to be fair, we can and should try using other objects as keys in the tests.

**Comment by sytong** [comment]
I will probably work on this next and I can look into #24 at the same time.

**Comment by buruzaemon** [comment]
Let's try to get this into our 0.0.3 release, by end-of-month?

**Comment by sytong** [comment]
Yup

**Comment by sytong** [comment]
Any idea of good source of test data in string?
A randomized list of book titles?
I wonder if there are free public data of library circulation we can use.

Or we just create some random data for ourselves?

**Comment by buruzaemon** [comment]
Actually, we are already counting occurrences of strings in the unit tests.

Brooke@iPhone

2015/03/23 0:05$B!"(Bsytong notifications@github.com $B$N%a%C%;!<%8(B:

**Comment by sytong** [comment]
Oh right the Pi values are read as String values.
So do we still need this?

**Comment by sytong** [comment]
Already covered by existing test cases.
