### ISSUE TITLE
Include Gemfile.lock in .gitignore

### ISSUE THREAD

**Issue by sytong** [buruzaemon/frequent-algorithm#32]
I saw that `Gemfile.lock` has been comment out. Intentional?

```
# for a library or gem, you might want to ignore these files since the code is
# intended to run in multiple environments; otherwise, check them in:
# Gemfile.lock
# .ruby-version
# .ruby-gemset
```

**Comment by buruzaemon** [comment]
.gitignore was generated automagically. Of course, it had no idea we were going to create a gem at the start, so we should uncomment this one, just to be correct.

**Comment by sytong** [comment]
Fixed in Pull Request https://github.com/buruzaemon/frequent-algorithm/pull/34
