### ISSUE TITLE
Quickselect should only work on sets (lists of unique items)

### ISSUE THREAD

**Issue by buruzaemon** [buruzaemon/frequent-algorithm#33]
For the calculation of kth largest item to be absolutely correct, we need to fix our implementation.

Originally, it was purposefully implemented to work on lists where items could repeat, but we should really follow the description of Ch. 9 in Introduction to Algorithms. 

**Input**: A set _A_ of _n_ (distinct) numbers and a number _k_, with 1 &le; _k_ &le; _n_
**Output**: The element _x_ &isin; _A_ that is larger than exactly _k_ - 1 other elements of _A_

**Comment by buruzaemon** [comment]
This algorithm does not assume that the argument list is sorted. 

Sorting the list ahead of time defeats the purpose of this algorithm. Best-case performance of a merge or heapsort is _O(n lg n)_, while quickselect should be _O(n)_.

**Comment by sytong** [comment]
Where can I find Chapter 9, I wonder?

**Comment by buruzaemon** [comment]
The book normally can't be found for free, but here are some notes from a uni in NY.

https://www.cs.rochester.edu/~gildea/csc282/slides/C09-median.pdf

**Comment by buruzaemon** [comment]
Another possibly good source of references would be this [question on SO](http://stackoverflow.com/questions/3260653/algorithm-to-find-top-10-search-terms).

**Comment by buruzaemon** [comment]
The only part to fix is the case where _k_ exceeds the length of the 'uniquifed' list.

In such a case, we will opt to assign to _k_ the length of the 'uniquifed' list.

**Comment by sytong** [comment]
I think calling Hash#values to get the list of items first is probably not recommended too as that requires going through every items in the summary first?

**Comment by buruzaemon** [comment]
No matter which data structure we choose, we will have to gather up the counts for each key, regardless. And recall that a Hash guarantees keys that are non-`nil` and unique (the keys form a set), plus access to the count for a given key is _O(1)_.

**Comment by buruzaemon** [comment]
Fix checked in and merged.
