### ISSUE TITLE
Enhance algorithm: Accept one element as parameter in the process method

### ISSUE THREAD

**Issue by sytong** [buruzaemon/frequent-algorithm#42]
Refactor the process method so that it can closely resembles the original algorithm

**Comment by sytong** [comment]
A really simple approach
- move the current algorithm logic to a private method, say, `_process`.
- maintain another array called `window`
- in `process`, store the element in `window` and call `_process`
- `_process` will check if the window size has reached `b`. If yes, process the current the window and empty it; otherwise do nothing.

Question: Is Thread Safety a concern here?

**Comment by buruzaemon** [comment]
I say we ignore thread safety at this point. No need to over-engineer.

**Comment by sytong** [comment]
Submitted Pull Request #47

**Comment by sytong** [comment]
I believe this one can be closed?

**Comment by buruzaemon** [comment]
Yeahp, closing this one and prepping for 0.0.4 release.
