### ISSUE TITLE
Hook up with Twitter API

### ISSUE THREAD

**Issue by buruzaemon** [buruzaemon/frequent-algorithm#5]
How about tweeting any commits, releases, etc.?

**Comment by sytong** [comment]
Let's take a look at this thread: http://stackoverflow.com/questions/2652983/is-there-a-script-that-posts-git-commits-to-twitter

And in particular: https://github.com/github/github-services/blob/master/lib/services/twitter.rb

**Comment by buruzaemon** [comment]
Ah, I think all we have to do is specify a Twitter account to set up a service hook. I set up mine for my other projects. 

You can try yours, if you like.

**Comment by buruzaemon** [comment]
Can you see this page under Settings?

https://github.com/buruzaemon/frequent-algorithm/settings/hooks

The service hook for Twitter is in the pull-down in there.

**Comment by sytong** [comment]
I saw someone dressed like Obi-Wan Kenobi telling me that was not the web page I was looking for.

I have access to the settings > hooks page of my own fork though.

**Comment by buruzaemon** [comment]
haha, ok... i can try setting up my twitter account.. just for kicks.

**Comment by buruzaemon** [comment]
Hooked up this project with Twitter user 'buruzaemon'.

You should see tweets on frequent-algorithm coming out on buruzaemon from now on.
