### ISSUE TITLE
Update Readme.md to reflect the latest API

### ISSUE THREAD

**Issue by sytong** [buruzaemon/frequent-algorithm#56]
In the Readme, we are still using the previous API `alg.statistics.report`.
In fact, it should be simply `alg.report` now.

**Comment by buruzaemon** [comment]
Yes indeed, there are little corrections like this that need... uh... correcting.

Brooke@iPhone

2015/06/15 19:05$B!"(BWillie SY Tong notifications@github.com $B$N%a%C%;!<%8(B:

**Comment by sytong** [comment]
Done
